const listProd = [
    { 
  id:'0',
  name:'Brahma',
  description:'',
  price:'R$ 4,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'1',
  name:'Itaipava',
  description:'',
  price:'R$ 3,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'2',
  name:'Original',
  description:'',
  price:'R$ 6,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'3',
  name:'Heineken',
  description:'',
  price:'R$ 6,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'4',
  name:'Imperio e petra',
  description:'',
  price:'R$ 4,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'5',
  name:'Refri',
  description:'',
  price:'R$ 5,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'6',
  name:'Long h',
  description:'',
  price:'R$ 8,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'7',
  name:'Long bad',
  description:'',
  price:'R$ 7,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'8',
  name:'Estela',
  description:'',
  price:'R$ 8,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'9',
  name:'Corona',
  description:'',
  price:'R$ 9,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'10',
  name:'Red Bull',
  description:'',
  price:'R$ 12,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'11',
  name:'Monster',
  description:'',
  price:'R$ 12,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'12',
  name:'Vinho Santome',
  description:'',
  price:'R$ 22,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'13',
  name:'Coca',
  description:'',
  price:'R$ 12,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'14',
  name:'Refri',
  description:'',
  price:'R$ 10,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'15',
  name:'Vinho',
  description:'',
  price:'R$ 8,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'16',
  name:'Gelo coco',
  description:'',
  price:'R$ 4,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'17',
  name:'Ice',
  description:'',
  price:'R$ 7,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'18',
  name:'Tônica',
  description:'',
  price:'R$ 5,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'19',
  name:'Vinho Drafrit',
  description:'',
  price:'R$ 14,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'20',
  name:'Red',
  description:'',
  price:'R$ 100,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'21',
  name:'Bad Lata',
  description:'',
  price:'R$ 5,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'22',
  name:'Sminorf Ice',
  description:'',
  price:'R$ 13,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'23',
  name:'Corote', 
  description:'',  
  price:'R$ 5,50',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'24',
  name:'Halls',
  description:'',   
  price:'R$ 3,00',
  img:'thumb.png',
  quantidade: 0,
},{ 
  id:'25',
  name:'Black Label',
  description:'',  
  price:'R$ 140,00',
  img:' ',
  quantidade: 0,
},{ 
  id:'26',
  name:'Itaipava 0%',
  description:'',  
  price:'R$ 5,00',
  img:' ',
  quantidade: 0,
},{ 
      id:'27',
      name:'Brahma 0%',
      description:'',
      price:'R$ 6,00',
      img:'hamburgueradc.png',
      quantidade: 0,
    },{ 
      id:'28',
      name:'Guaraná 1L',
      description:'',
      price:'R$ 5,00',
      img:'salsicha.png',
      quantidade: 0,
    },{ 
      id:'29',
      name:'Itaipava Malzbier',
      description:'',
      price:'R$ 6,50',
      img:'ovos.png',
      quantidade: 0,
    },{ 
      id:'30',
      name:'Sminorf Lata',
      description:'',
      price:'R$ 9,50',
      img:'bacon.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Skol',
      description:'',
      price:'R$ 36,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Brahma',
      description:'',
      price:'R$ 38,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Heineken',
      description:'',
      price:'R$ 59,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Original',
      description:'',
      price:'R$ 54,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Badweiser',
      description:'',
      price:'R$ 28,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Petra',
      description:'',
      price:'R$ 38,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Eisenbahn',
      description:'',
      price:'R$ 65,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Spaten',
      description:'',
      price:'R$ 59,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Spaten Unidade',
      description:'',
      price:'R$ 6,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Império unidade',
      description:'',
      price:'R$ 4,50',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fardo Império',
      description:'',
      price:'R$ 37,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Jurupinga',
      description:'',
      price:'R$ 35,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Velho Barreiro',
      description:'',
      price:'R$ 18,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Famous One whisky',
      description:'',
      price:'R$ 25,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Master Gold',
      description:'',
      price:'R$ 25,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Jack Whisky',
      description:'',
      price:'R$ 120,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Contini',
      description:'',
      price:'R$ 38,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Gold Label',
      description:'',
      price:'R$ 190,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Ballantines',
      description:'',
      price:'R$ 99,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Gin Tanqueray',
      description:'',
      price:'R$ 199,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Gin Rose',
      description:'',
      price:'R$ 28,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Dreher',
      description:'',
      price:'R$ 21,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'51 Pinga',
      description:'',
      price:'R$ 18,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Pitu Pinga',
      description:'',
      price:'R$ 25,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Old star',
      description:'',
      price:'R$ 20,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Passaport',
      description:'',
      price:'R$ 55,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Black stone',
      description:'',
      price:'R$ 35,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Askov',
      description:'',
      price:'R$ 18,50',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Sminorf Sabor',
      description:'',
      price:'R$ 58,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Água 1,5L',
      description:'',
      price:'R$ 5,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Petra',
      description:'',
      price:'R$ 5,50',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Brahma duplemalte',
      description:'',
      price:'R$ 5,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Fofura',
      description:'',
      price:'R$ 4,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Torcida',
      description:'',
      price:'R$ 3,00',
      img:'calabresa.png',
      quantidade: 0,
    },{ 
      id:'31',
      name:'Gin',
      description:'',
      price:'R$ 130,00',
      img:'calabresa.png',
      quantidade: 0,
    } 
]